---
# Latest from official repo!
- name: Add the HashiCorp GPG key.
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: get Architecture
  set_fact:
    arch: "{{ {'arm': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] | default('') }}"

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{arch}}] https://apt.releases.hashicorp.com {{codename}} main"
    state: present

- name: install
  ansible.builtin.apt:
    pkg:
    - packer
